name: Update GFWList

on:
  schedule:
    - cron: "0 18 * * *" # This is 2:00 AM Beijing time (UTC+8)
  workflow_dispatch: # Allows manual triggering

jobs:
  update-gfwlist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests PyGithub

      - name: Run update script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: python gfwlist_downloader.py

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Update Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          name: Latest GFWList
          body: Updated on ${{ steps.date.outputs.date }}
          files: gfwlist.txt
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
